kind: pipeline
name: CI
type: docker

trigger:
  event:
    - push
  ref:
    exclude:
      - refs/heads/dependabot/npm_and_yarn/*

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: rebuild
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    volumes:
      - name: pnpm-store
        path: /drone/src/.pnpm-store
    commands:
      - pnpm install
