kind: pipeline
name: CI
type: docker

trigger:
  event:
    - push

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: rebuild
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    volumes:
      - name: pnpm-store
        path: /root/.pnpm-store
    commands:
      - pnpm install
      - echo "$PWD"
      - ls -a .pnpm-store/v10
