kind: pipeline
name: CI
type: docker

trigger:
  event:
    - push
    - tag
  ref:
    include:
      - refs/heads/dev
      - refs/heads/feature/*
      - refs/heads/rfc/*
      - refs/heads/bugfix/*
      - refs/heads/improvement/*
      - refs/heads/prerelease/*
      - refs/heads/library/*
      - refs/heads/hotfix/*
      - refs/heads/*.*.x
      - refs/tags/*

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: rebuild
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    volumes:
      - name: pnpm-store
        path: /root/.pnpm-store
    commands:
      - pnpm install
