kind: pipeline
name: CI
type: docker

trigger:
  event:
    - push
    - tag

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: build
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    volumes:
      - name: pnpm-store
        path: /root/.pnpm-store
    environment:
      NEXUS_DEPLOYER_USERNAME:
        from_secret: NEXUS_DEPLOYER_USERNAME
      NEXUS_DEPLOYER_PASSWORD:
        from_secret: NEXUS_DEPLOYER_PASSWORD
    commands:
      # - yamllint .
      - pnpm install && pnpm lint
      - pnpm formatter:check
