ARG BASE_IMAGE

#FROM $BASE_IMAGE
FROM know-how.download/library/nginx-runner

LABEL maintainer="maintainer@knowhowto.dev"
ARG VCS_REFERENCE
ARG BUILD_VERSION_REFERENCE
ARG SOURCE_DIR

ENV APPLICATION_VCS_REFERENCE ${VCS_REFERENCE}
ENV APPLICATION_BUILD_VERSION ${BUILD_VERSION_REFERENCE}

COPY ${SOURCE_DIR} /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]